# Generated by Django 2.1.7 on 2019-03-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centrals',
            fields=[
                ('objid', models.IntegerField(null=True)),
                ('morphtype', models.CharField(max_length=6, null=True)),
                ('ra', models.FloatField(null=True)),
                ('dec', models.FloatField(null=True)),
                ('mem_match_id', models.FloatField(null=True)),
                ('mem_match_id_string', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('z', models.FloatField(null=True)),
                ('la', models.FloatField(null=True)),
                ('sdss_objid', models.FloatField(null=True)),
                ('viewer_link', models.CharField(max_length=100, null=True)),
                ('skyserver_link', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
